// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJKR0QrzUAdOhMTEY0RH_s0XN85kVJupg',
    appId: '1:399010243351:web:83a723a25ab684dc9e0d52',
    messagingSenderId: '399010243351',
    projectId: 'evenement-ee6d6',
    authDomain: 'evenement-ee6d6.firebaseapp.com',
    databaseURL: 'https://evenement-ee6d6.firebaseio.com',
    storageBucket: 'evenement-ee6d6.appspot.com',
    measurementId: 'G-BN8H8PEXF1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBa04MdxxTTZFxAmMrBM7FOPSGIXZ4rg9o',
    appId: '1:399010243351:android:8e8a3bb47aba8fee9e0d52',
    messagingSenderId: '399010243351',
    projectId: 'evenement-ee6d6',
    databaseURL: 'https://evenement-ee6d6.firebaseio.com',
    storageBucket: 'evenement-ee6d6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlgqV7k5osALwkV5-xyuOcN4TVUxqWe48',
    appId: '1:399010243351:ios:443a8d2e10b855cd9e0d52',
    messagingSenderId: '399010243351',
    projectId: 'evenement-ee6d6',
    databaseURL: 'https://evenement-ee6d6.firebaseio.com',
    storageBucket: 'evenement-ee6d6.appspot.com',
    iosClientId: '399010243351-98n1oqebggi3odbq3q8839m1lnbb27u9.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
